import type { BusinessProcess } from '@/types/process'
import { analyzeProcessConformance } from './conformance'

/**
 * 1. Выдача кредита юридическим лицам (SQB Business Credit)
 */
export const sqbCreditProcess: BusinessProcess = {
  id: 'proc-sqb-cred-001',
  name: 'Выдача кредита юридическим лицам',
  fileName: 'process.drawio',
  passport: {
    code: 'PRC-SQB-CRED-001',
    name: 'Регламент предоставления кредитов корпоративным клиентам и МСБ',
    version: '2.4',
    status: 'active',
    owner: 'Департамент корпоративного кредитования АКБ «Узпромстройбанк»',
    department: 'Управление кредитования малого и среднего бизнеса',
    category: 'Кредитные операции ЮЛ',
    targetSlaHours: 24,
    description:
      'Сквозной регламент рассмотрения кредитных заявок юридических лиц от первичного приема до выдачи транша в АБС ЦФТ-Банк с автоматической проверкой через PIX RPA.',
    createdDate: '2026-01-15',
    updatedDate: '2026-08-24',
  },
  lanes: [
    {
      id: 'lane-front',
      name: 'Фронт-офис (Кредитный эксперт)',
      type: 'lane',
      role: 'Кредитный эксперт филиала',
      geometry: { x: 70, y: 40, width: 1530, height: 180 },
      style: 'swimlane;horizontal=0;',
    },
    {
      id: 'lane-rpa',
      name: 'PIX RPA & Автоматические сервисы',
      type: 'lane',
      role: 'Робот PIX RPA / Интеграция АБС',
      geometry: { x: 70, y: 220, width: 1530, height: 180 },
      style: 'swimlane;horizontal=0;',
    },
    {
      id: 'lane-risk',
      name: 'Служба рисков и безопасности (СБ)',
      type: 'lane',
      role: 'Андеррайтер / Риск-офицер',
      geometry: { x: 70, y: 400, width: 1530, height: 180 },
      style: 'swimlane;horizontal=0;',
    },
    {
      id: 'lane-comm',
      name: 'Кредитный комитет',
      type: 'lane',
      role: 'Члены кредитного комитета',
      geometry: { x: 70, y: 580, width: 1530, height: 180 },
      style: 'swimlane;horizontal=0;',
    },
    {
      id: 'lane-back',
      name: 'Бэк-офис и учет (АБС)',
      type: 'lane',
      role: 'Бухгалтер-контролер / АБС',
      geometry: { x: 70, y: 760, width: 1530, height: 180 },
      style: 'swimlane;horizontal=0;',
    },
  ],
  nodes: [
    // Lane 1: Front
    {
      id: 'node-start',
      code: 'START',
      name: 'Поступление кредитной заявки',
      type: 'startEvent',
      category: 'notification',
      laneId: 'lane-front',
      laneName: 'Фронт-офис (Кредитный эксперт)',
      role: 'Кредитный эксперт филиала',
      system: 'SQB Business Portal / CRM',
      slaMinutes: 10,
      costPerExecution: 5000,
      automationPotential: 80,
      description: 'Заявка поступает через портал банка или при личном визите клиента в филиал.',
      geometry: { x: 110, y: 105, width: 48, height: 48 },
      style: 'ellipse;',
    },
    {
      id: 'node-step-1',
      code: 'STEP-01',
      name: 'Первичная проверка и сбор документов',
      type: 'userTask',
      category: 'manual',
      laneId: 'lane-front',
      laneName: 'Фронт-офис (Кредитный эксперт)',
      role: 'Кредитный эксперт филиала',
      system: 'SQB CRM / Document Hub',
      slaMinutes: 60,
      costPerExecution: 25000,
      automationPotential: 65,
      description: 'Проверка учредительных документов, баланса, формы 1 и 2 за последние 4 квартала.',
      inputArtifacts: ['Заявление на кредит', 'Финотчетность', 'Устав ЮЛ'],
      outputArtifacts: ['Кредитное досье (электронное)'],
      geometry: { x: 220, y: 95, width: 170, height: 70 },
      style: 'rounded=1;',
    },
    // Lane 2: RPA
    {
      id: 'node-step-2',
      code: 'STEP-02',
      name: 'Авто-скоринг & Проверка ГНК (Soliq) / KATM',
      type: 'serviceTask',
      category: 'rpa_bot',
      laneId: 'lane-rpa',
      laneName: 'PIX RPA & Автоматические сервисы',
      role: 'Робот PIX RPA',
      system: 'PIX RPA / API KATM / API Soliq (ГНК)',
      slaMinutes: 5,
      costPerExecution: 800,
      automationPotential: 95,
      description:
        'Робот PIX автоматически запрашивает кредитную историю в КАТМ, налоговую задолженность в ГНК и реестр залогов.',
      inputArtifacts: ['ИНН компании', 'Паспортные данные учредителей'],
      outputArtifacts: ['Скоринговый отчет KATM', 'Справка ГНК об отсутствии долгов'],
      geometry: { x: 430, y: 275, width: 190, height: 70 },
      style: 'rounded=1;fillColor=#dcfce7;',
    },
    // Lane 3: Risk
    {
      id: 'node-step-3',
      code: 'STEP-03',
      name: 'Андеррайтинг и оценка рисков / залога',
      type: 'userTask',
      category: 'validation',
      laneId: 'lane-risk',
      laneName: 'Служба рисков и безопасности (СБ)',
      role: 'Андеррайтер / Риск-офицер',
      system: 'SQB Risk Engine / Реестр залогов',
      slaMinutes: 180,
      costPerExecution: 45000,
      automationPotential: 40,
      description: 'Глубокий финансовый анализ денежных потоков, оценка ликвидности залогового имущества.',
      inputArtifacts: ['Скоринговый отчет', 'Оценка залога'],
      outputArtifacts: ['Заключение риск-департамента'],
      geometry: { x: 670, y: 455, width: 180, height: 70 },
      style: 'rounded=1;',
    },
    {
      id: 'node-gw-risk',
      code: 'GW-RISK',
      name: 'Риск допустим?',
      type: 'exclusiveGateway',
      laneId: 'lane-risk',
      laneName: 'Служба рисков и безопасности (СБ)',
      role: 'Андеррайтер / Риск-офицер',
      geometry: { x: 900, y: 467, width: 46, height: 46 },
      style: 'rhombus;',
    },
    // Lane 4: Committee
    {
      id: 'node-step-4',
      code: 'STEP-04',
      name: 'Рассмотрение Кредитным комитетом',
      type: 'userTask',
      category: 'approval',
      laneId: 'lane-comm',
      laneName: 'Кредитный комитет',
      role: 'Члены кредитного комитета',
      system: 'Портал голосования SQB Committee',
      slaMinutes: 240,
      costPerExecution: 60000,
      automationPotential: 30,
      description: 'Электронное голосование членов комитета с цифровой подписью ЭЦП.',
      inputArtifacts: ['Заключение рисков', 'Проект решения'],
      outputArtifacts: ['Протокол заседания Кредитного комитета'],
      geometry: { x: 1000, y: 635, width: 180, height: 70 },
      style: 'rounded=1;',
    },
    {
      id: 'node-gw-comm',
      code: 'GW-COMM',
      name: 'Кредит одобрен?',
      type: 'exclusiveGateway',
      laneId: 'lane-comm',
      laneName: 'Кредитный комитет',
      role: 'Члены кредитного комитета',
      geometry: { x: 1230, y: 647, width: 46, height: 46 },
      style: 'rhombus;',
    },
    // Lane 2: RPA Auto-Contract
    {
      id: 'node-step-5',
      code: 'STEP-05',
      name: 'PIX RPA Генерация договора и счета в АБС',
      type: 'serviceTask',
      category: 'rpa_bot',
      laneId: 'lane-rpa',
      laneName: 'PIX RPA & Автоматические сервисы',
      role: 'Робот PIX RPA',
      system: 'PIX RPA / АБС ЦФТ-Банк',
      slaMinutes: 10,
      costPerExecution: 1200,
      automationPotential: 90,
      description:
        'Робот формирует кредитный договор по шаблону и создает ссудный счет 16... в АБС ЦФТ.',
      inputArtifacts: ['Протокол комитета', 'Реквизиты заемщика'],
      outputArtifacts: ['Кредитный договор (PDF)', 'Номер ссудного счета в АБС'],
      geometry: { x: 1300, y: 275, width: 190, height: 70 },
      style: 'rounded=1;fillColor=#dcfce7;',
    },
    // Lane 5: Back
    {
      id: 'node-step-6',
      code: 'STEP-06',
      name: 'Подписание Didox (ЭДО) и зачисление средств',
      type: 'userTask',
      category: 'manual',
      laneId: 'lane-back',
      laneName: 'Бэк-офис и учет (АБС)',
      role: 'Бухгалтер-контролер / АБС',
      system: 'АБС ЦФТ-Банк / Didox (ЭДО)',
      slaMinutes: 60,
      costPerExecution: 20000,
      automationPotential: 70,
      description: 'Подписание договора клиентом в Didox и проведение банковской проводки зачисления кредита.',
      inputArtifacts: ['Подписанный договор с ЭЦП'],
      outputArtifacts: ['Мемориальный ордер', 'Выписка по ссудному счету'],
      geometry: { x: 1310, y: 815, width: 180, height: 70 },
      style: 'rounded=1;',
    },
    {
      id: 'node-end',
      code: 'END',
      name: 'Кредит успешно выдан',
      type: 'endEvent',
      category: 'notification',
      laneId: 'lane-back',
      laneName: 'Бэк-офис и учет (АБС)',
      role: 'АБС ЦФТ',
      geometry: { x: 1535, y: 826, width: 48, height: 48 },
      style: 'ellipse;',
    },
    {
      id: 'node-reject',
      code: 'REJECT',
      name: 'Отказ / Архив',
      type: 'endEvent',
      category: 'notification',
      laneId: 'lane-risk',
      laneName: 'Служба рисков и безопасности (СБ)',
      role: 'Андеррайтер',
      geometry: { x: 899, y: 525, width: 48, height: 48 },
      style: 'ellipse;fillColor=#ef4444;',
    },
  ],
  edges: [
    {
      id: 'edge-1',
      name: '',
      sourceId: 'node-start',
      targetId: 'node-step-1',
      points: [],
    },
    {
      id: 'edge-2',
      name: 'Досье готово',
      sourceId: 'node-step-1',
      targetId: 'node-step-2',
      points: [],
    },
    {
      id: 'edge-3',
      name: 'Скоринг готов',
      sourceId: 'node-step-2',
      targetId: 'node-step-3',
      points: [],
    },
    {
      id: 'edge-4',
      name: '',
      sourceId: 'node-step-3',
      targetId: 'node-gw-risk',
      points: [],
    },
    {
      id: 'edge-5',
      name: 'Да (Одобрено)',
      condition: 'risk_level <= 3',
      sourceId: 'node-gw-risk',
      targetId: 'node-step-4',
      points: [],
    },
    {
      id: 'edge-risk-no',
      name: 'Отказ',
      sourceId: 'node-gw-risk',
      targetId: 'node-reject',
      points: [],
    },
    {
      id: 'edge-6',
      name: '',
      sourceId: 'node-step-4',
      targetId: 'node-gw-comm',
      points: [],
    },
    {
      id: 'edge-7',
      name: 'Одобрено',
      condition: 'committee_decision == "APPROVED"',
      sourceId: 'node-gw-comm',
      targetId: 'node-step-5',
      points: [],
    },
    {
      id: 'edge-8',
      name: 'Счет в АБС открыт',
      sourceId: 'node-step-5',
      targetId: 'node-step-6',
      points: [],
    },
    {
      id: 'edge-9',
      name: 'Выдано',
      sourceId: 'node-step-6',
      targetId: 'node-end',
      points: [],
    },
  ],
  validation: [],
  registry: {
    id: 'reg-sqb-cred',
    name: 'Реестр кредитных заявок ЮЛ (SQB Business)',
    code: 'REG_CREDIT_CORP',
    description: 'Единый реестр входящих заявок корпоративного кредитования АКБ «Узпромстройбанк»',
    fields: [
      { id: 'f1', code: 'inn', name: 'ИНН компании', type: 'string', required: true },
      { id: 'f2', code: 'company_name', name: 'Наименование ЮЛ', type: 'string', required: true },
      { id: 'f3', code: 'amount_uzs', name: 'Сумма кредита (UZS)', type: 'number', required: true },
      { id: 'f4', code: 'term_months', name: 'Срок (мес.)', type: 'number', required: true },
      { id: 'f5', code: 'interest_rate', name: 'Ставка (%)', type: 'number', required: true },
      { id: 'f6', code: 'katm_score', name: 'Скоринг KATM', type: 'number', required: false },
      { id: 'f7', code: 'risk_decision', name: 'Решение рисков', type: 'select', required: true, options: ['Одобрено', 'Отклонено', 'На доработку'] },
      { id: 'f8', code: 'abs_account', name: 'Ссудный счет АБС', type: 'string', required: false },
    ],
    records: [
      {
        id: 'rec-001',
        caseId: 'SQB-2026-0041',
        createdAt: '2026-08-23 09:15',
        status: 'in_progress',
        currentStepId: 'node-step-4',
        currentStepName: 'Рассмотрение Кредитным комитетом',
        assignedTo: 'Комитет ГО (Предс. Каримов А.)',
        elapsedMinutes: 320,
        data: {
          inn: '305128994',
          company_name: 'OOO "TOSHKENT TEXTILE GROUP"',
          amount_uzs: 4500000000,
          term_months: 36,
          interest_rate: 21.5,
          katm_score: 740,
          risk_decision: 'Одобрено',
          abs_account: '16103000800049281001',
        },
      },
      {
        id: 'rec-002',
        caseId: 'SQB-2026-0042',
        createdAt: '2026-08-23 10:40',
        status: 'completed',
        currentStepId: 'node-end',
        currentStepName: 'Кредит успешно выдан',
        assignedTo: 'Бухгалтерия (Юсупова Д.)',
        elapsedMinutes: 720,
        data: {
          inn: '201948572',
          company_name: 'СП "SAMARQAND AGRO LOGISTICS"',
          amount_uzs: 1800000000,
          term_months: 24,
          interest_rate: 22.0,
          katm_score: 810,
          risk_decision: 'Одобрено',
          abs_account: '16103000900051294002',
        },
      },
      {
        id: 'rec-003',
        caseId: 'SQB-2026-0043',
        createdAt: '2026-08-23 11:20',
        status: 'delayed',
        currentStepId: 'node-step-3',
        currentStepName: 'Андеррайтинг и оценка рисков / залога',
        assignedTo: 'Риск-менеджер (Султанов Ш.)',
        elapsedMinutes: 480,
        data: {
          inn: '308941205',
          company_name: 'ЧП "BUXORO MEBEL SERVIS"',
          amount_uzs: 850000000,
          term_months: 18,
          interest_rate: 23.5,
          katm_score: 620,
          risk_decision: 'На доработку',
          abs_account: '-',
        },
      },
      {
        id: 'rec-004',
        caseId: 'SQB-2026-0044',
        createdAt: '2026-08-23 14:05',
        status: 'in_progress',
        currentStepId: 'node-step-2',
        currentStepName: 'Авто-скоринг & Проверка ГНК (PIX RPA)',
        assignedTo: 'Робот PIX RPA #02',
        elapsedMinutes: 4,
        data: {
          inn: '204859124',
          company_name: 'OOO "FERGANA PHARM DISTRIB"',
          amount_uzs: 3200000000,
          term_months: 36,
          interest_rate: 21.0,
          katm_score: 790,
          risk_decision: 'Одобрено',
          abs_account: 'В процессе',
        },
      },
    ],
  },
  miningMetrics: {
    totalCases: 420,
    conformanceRate: 74.2,
    avgLeadTimeHours: 33.1,
    targetLeadTimeHours: 24.0,
    slaBreachRate: 25.8,
    reworkRate: 18.5,
    potentialRpaSavingsUzs: 173000000,
    deviations: [],
  },
}
sqbCreditProcess.miningMetrics = analyzeProcessConformance(sqbCreditProcess)

/**
 * 2. Открытие расчетного счета ИП и ЮЛ (SQB Fast Onboarding)
 */
export const sqbAccountProcess: BusinessProcess = {
  id: 'proc-sqb-acc-002',
  name: 'Дистанционное открытие расчетного счета ЮЛ/ИП',
  fileName: 'sqb_account_onboarding.drawio',
  passport: {
    code: 'PRC-SQB-ACC-002',
    name: 'Регламент быстрого онбординга и открытия счетов корпоративным клиентам',
    version: '1.8',
    status: 'active',
    owner: 'Департамент цифрового банкинга и транзакционного бизнеса',
    department: 'Управление расчетно-кассового обслуживания',
    category: 'Расчетно-кассовое обслуживание',
    targetSlaHours: 2,
    description:
      'Автоматизированный процесс открытия основного расчетного счета 20208... через мобильное приложение SQB Business с проверкой в ГНК и комплаенс-фильтрами.',
    createdDate: '2026-02-10',
    updatedDate: '2026-08-18',
  },
  lanes: [
    {
      id: 'lane-acc-client',
      name: 'Клиент / Онлайн-заявка',
      type: 'lane',
      geometry: { x: 70, y: 40, width: 1400, height: 160 },
      style: 'swimlane;horizontal=0;',
    },
    {
      id: 'lane-acc-rpa',
      name: 'PIX RPA & Сервисы ЕПИГУ / ГНК',
      type: 'lane',
      geometry: { x: 70, y: 200, width: 1400, height: 160 },
      style: 'swimlane;horizontal=0;',
    },
    {
      id: 'lane-acc-comp',
      name: 'Комплаенс & Финмониторинг',
      type: 'lane',
      geometry: { x: 70, y: 360, width: 1400, height: 160 },
      style: 'swimlane;horizontal=0;',
    },
    {
      id: 'lane-acc-abs',
      name: 'АБС ЦФТ / Выпуск реквизитов',
      type: 'lane',
      geometry: { x: 70, y: 520, width: 1400, height: 160 },
      style: 'swimlane;horizontal=0;',
    },
  ],
  nodes: [
    {
      id: 'acc-start',
      code: 'START',
      name: 'Онлайн заявка на открытие счета',
      type: 'startEvent',
      laneId: 'lane-acc-client',
      laneName: 'Клиент / Онлайн-заявка',
      geometry: { x: 110, y: 95, width: 48, height: 48 },
      style: 'ellipse;whiteSpace=wrap;html=1;',
    },
    {
      id: 'acc-step-1',
      code: 'STEP-01',
      name: 'PIX RPA: Валидация выписки ЕГРПО & Бенефициаров',
      type: 'serviceTask',
      category: 'rpa_bot',
      laneId: 'lane-acc-rpa',
      laneName: 'PIX RPA & Сервисы ЕПИГУ / ГНК',
      role: 'Робот PIX RPA',
      system: 'API ЕПИГУ / ЕГРПО',
      slaMinutes: 3,
      costPerExecution: 400,
      automationPotential: 98,
      geometry: { x: 230, y: 245, width: 190, height: 70 },
      style: 'rounded=1;whiteSpace=wrap;html=1;fillColor=#d5e8d4;',
    },
    {
      id: 'acc-step-2',
      code: 'STEP-02',
      name: 'Авто-проверка по черным спискам и санкциям (WorldCheck)',
      type: 'serviceTask',
      category: 'rpa_bot',
      laneId: 'lane-acc-comp',
      laneName: 'Комплаенс & Финмониторинг',
      role: 'Робот PIX / WorldCheck API',
      system: 'SQB Sanctions Engine',
      slaMinutes: 5,
      costPerExecution: 600,
      automationPotential: 90,
      geometry: { x: 490, y: 405, width: 200, height: 70 },
      style: 'rounded=1;whiteSpace=wrap;html=1;',
    },
    {
      id: 'acc-step-3',
      code: 'STEP-03',
      name: 'Генерация счета 20208... в АБС ЦФТ и SMS-нотификация',
      type: 'serviceTask',
      category: 'api_service',
      laneId: 'lane-acc-abs',
      laneName: 'АБС ЦФТ / Выпуск реквизитов',
      role: 'АБС ЦФТ-Банк',
      system: 'АБС ЦФТ-Банк / SMS Gateway',
      slaMinutes: 2,
      costPerExecution: 500,
      automationPotential: 100,
      geometry: { x: 760, y: 565, width: 210, height: 70 },
      style: 'rounded=1;whiteSpace=wrap;html=1;fillColor=#d5e8d4;',
    },
    {
      id: 'acc-end',
      code: 'END',
      name: 'Счет активирован, реквизиты выданы',
      type: 'endEvent',
      laneId: 'lane-acc-abs',
      laneName: 'АБС ЦФТ / Выпуск реквизитов',
      geometry: { x: 1040, y: 576, width: 48, height: 48 },
      style: 'ellipse;whiteSpace=wrap;html=1;',
    },
  ],
  edges: [
    { id: 'acc-e1', name: '', sourceId: 'acc-start', targetId: 'acc-step-1', points: [] },
    { id: 'acc-e2', name: 'Данные валидны', sourceId: 'acc-step-1', targetId: 'acc-step-2', points: [] },
    { id: 'acc-e3', name: 'Санкций нет', sourceId: 'acc-step-2', targetId: 'acc-step-3', points: [] },
    { id: 'acc-e4', name: 'Готово', sourceId: 'acc-step-3', targetId: 'acc-end', points: [] },
  ],
  validation: [],
  registry: {
    id: 'reg-sqb-acc',
    name: 'Реестр заявок на открытие счетов ЮЛ',
    code: 'REG_ACCOUNT_OPENING',
    description: 'Журнал онбординга новых клиентов АКБ «Узпромстройбанк»',
    fields: [
      { id: 'fa1', code: 'inn', name: 'ИНН', type: 'string', required: true },
      { id: 'fa2', code: 'company_name', name: 'Компания', type: 'string', required: true },
      { id: 'fa3', code: 'director_pinfl', name: 'ПИНФЛ Директора', type: 'string', required: true },
      { id: 'fa4', code: 'account_number', name: 'Номер счета 20208...', type: 'string', required: false },
      { id: 'fa5', code: 'sanction_status', name: 'Статус санкций', type: 'select', required: true, options: ['CLEAN', 'MANUAL_CHECK'] },
    ],
    records: [
      {
        id: 'rec-acc-1',
        caseId: 'ACC-2026-0811',
        createdAt: '2026-08-24 08:30',
        status: 'completed',
        currentStepId: 'acc-end',
        currentStepName: 'Счет активирован',
        assignedTo: 'PIX Robot #01',
        elapsedMinutes: 8,
        data: {
          inn: '309118224',
          company_name: 'OOO "SILK ROAD LOGISTICS"',
          director_pinfl: '31405901230045',
          account_number: '20208000700591823001',
          sanction_status: 'CLEAN',
        },
      },
      {
        id: 'rec-acc-2',
        caseId: 'ACC-2026-0812',
        createdAt: '2026-08-24 09:10',
        status: 'in_progress',
        currentStepId: 'acc-step-2',
        currentStepName: 'Авто-проверка по черным спискам',
        assignedTo: 'Комплаенс-офицер',
        elapsedMinutes: 12,
        data: {
          inn: '203918451',
          company_name: 'ИП "RAXIMOV NODIR"',
          director_pinfl: '32009851120038',
          account_number: 'Формируется',
          sanction_status: 'CLEAN',
        },
      },
    ],
  },
  miningMetrics: {
    totalCases: 890,
    conformanceRate: 88.5,
    avgLeadTimeHours: 1.8,
    targetLeadTimeHours: 2.0,
    slaBreachRate: 11.5,
    reworkRate: 6.2,
    potentialRpaSavingsUzs: 84000000,
    deviations: [],
  },
}
sqbAccountProcess.miningMetrics = analyzeProcessConformance(sqbAccountProcess)

/**
 * All pre-loaded processes
 */
export const SAMPLE_PROCESSES = [sqbCreditProcess, sqbAccountProcess]
